# Generated by Django 5.1.3 on 2025-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Уникальное имя столика, например, 'Table 1'", max_length=50, unique=True, verbose_name='Название столика')),
                ('seats', models.PositiveSmallIntegerField(help_text='Введите количество посадочных мест за столиком', verbose_name='Количество мест')),
                ('location', models.CharField(help_text="Например, 'зал у окна' или 'терраса'", max_length=100, verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('seats__gte', 1)), name='min_seats_check')],
            },
        ),
    ]
