# Generated by Django 5.1.3 on 2025-04-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Введите имя клиента', max_length=100, verbose_name='Имя клиента')),
                ('reservation_time', models.DateTimeField(help_text='Укажите время бронирования', verbose_name='Время бронирования')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Укажите продолжительность бронирования в минутах', verbose_name='Продолжительность (в минутах)')),
                ('table', models.ForeignKey(help_text='Выберите столик для брони', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Table.table', verbose_name='Столик')),
            ],
        ),
    ]
